### ISSUE TITLE
Error reading the dictionary

### ISSUE THREAD

**Issue by thiziri** [cvangysel/pyndri#8]
Good morning, 
In order to perform my tests, I need to get all the  words for a document (for exemple get all the words of document 1), I used the snipet code that you gave in [https://arxiv.org/pdf/1701.00749.pdf](url) like this : 
`print([dictionary[token_id] for token_id in index.document(1)[1]])` I've gotten the following error : 
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "~local/lib/python3.5/site-packages/pyndri/dictionary.py", line 32, in __getitem__
    return self.id2token[token_id]
KeyError: 0`
Please, can you explain me how can I get access to all the document words ?
Thanks

**Comment by cvangysel** [comment]
This behaviour is by design. A token id of 0 indicates that the token is out of vocabulary. This can be due to stop word removal or the occurrence of tokens that consist of only non-alphanumerical characters.

The following works:

    print([dictionary[token_id] for token_id in index.document(1)[1] if token_id in dictionary])

These null tokens are included in order to preserve positional information.

**Comment by thiziri** [comment]
Thanks it works :+1:
